### ISSUE TITLE
Time to publish

### ISSUE THREAD

**Issue by Docmilo** [ShanewUU/TetrisGame#1]
Hey @ShanewUU how about we turn on GitHub pages and publish the game?

**Comment by ShanewUU** [comment]
@Docmilo maybe we should review the project files and ensure we are good to go. Can you create an issue and complete this task please?

**Comment by ShanewUU** [comment]
GitHub pages turned on and the game is published at [gameURL](https://shanewuu.github.io/TetrisGame/)
